packages:
  - "apps/api"
  - "apps/key-updaters/*"
  - "apps/cli"
  - "apps/judge"
  - "apps/portal"
  - "apps/token-manager"
  - "apps/workers/*"
  - "apps/model-scanners/*"
  - "apps/version-checkers/*"
  - "packages/shared"
  - "packages/version-checking"
  - "packages/github-auth"
  - "packages/model-scanning"
  - "packages/db-migrations"
