#!/usr/bin/env bash
# =============================================================================
# shared-infra-setup.sh — Deploy a shared dev CosmosDB for MongoDB account
# =============================================================================
# One-time setup per team. Creates a serverless CosmosDB account and stores
# the connection string in .env.shared-infra at the repo base folder so all
# worktrees can access it.
#
# Usage:
#   ./scripts/shared-infra-setup.sh [--resource-group <rg>] [--account-name <name>] [--location <loc>]
#
# Defaults:
#   resource-group: scope-dev-infra
#   account-name:   scope-dev-cosmosdb
#   location:       eastus2
# =============================================================================
set -euo pipefail

# Defaults
RESOURCE_GROUP="scope-dev-infra"
ACCOUNT_NAME="scope-dev-cosmosdb"
LOCATION="eastus2"

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --resource-group) RESOURCE_GROUP="$2"; shift 2 ;;
    --account-name)   ACCOUNT_NAME="$2"; shift 2 ;;
    --location)       LOCATION="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: $0 [--resource-group <rg>] [--account-name <name>] [--location <loc>]"
      exit 0 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_BASE="$(cd "$(git rev-parse --git-common-dir)/.." && pwd)"
BICEP_FILE="$SCRIPT_DIR/../infra/cosmosdb-dev.bicep"

echo "=== Shared Infrastructure Setup ==="
echo "  Resource Group: $RESOURCE_GROUP"
echo "  Account Name:   $ACCOUNT_NAME"
echo "  Location:       $LOCATION"
echo "  Bicep:          $BICEP_FILE"
echo "  Output:         $REPO_BASE/.env.shared-infra"
echo ""

# Ensure resource group exists
echo "→ Ensuring resource group '$RESOURCE_GROUP' exists..."
az group create --name "$RESOURCE_GROUP" --location "$LOCATION" --output none 2>/dev/null || true

# Deploy Bicep template
echo "→ Deploying CosmosDB account (this may take a few minutes)..."
DEPLOYMENT_OUTPUT=$(az deployment group create \
  --resource-group "$RESOURCE_GROUP" \
  --template-file "$BICEP_FILE" \
  --parameters accountName="$ACCOUNT_NAME" location="$LOCATION" \
  --query "properties.outputs" \
  --output json)

# Extract connection string
CONNECTION_STRING=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys, json; print(json.load(sys.stdin)['connectionString']['value'])")

if [ -z "$CONNECTION_STRING" ]; then
  echo "ERROR: Failed to retrieve connection string from deployment output."
  exit 1
fi

# Write to .env.shared-infra in the repo base folder
ENV_FILE="$REPO_BASE/.env.shared-infra"
cat > "$ENV_FILE" <<EOF
# =============================================================================
# Shared dev infrastructure — auto-generated by scripts/shared-infra-setup.sh
# =============================================================================
# This file is read by worktrees via 'pnpm shared-infra:use'.
# Do NOT commit this file (it is gitignored).
# =============================================================================
MONGO_CONNECTION_STRING=$CONNECTION_STRING
EOF

echo ""
echo "✓ CosmosDB account '$ACCOUNT_NAME' deployed successfully."
echo "✓ Connection string written to: $ENV_FILE"
echo ""
echo "Next steps:"
echo "  In each worktree, run: pnpm shared-infra:use"
