// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import { useParams, Link } from "react-router-dom";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "@/components/ui/table";
import {
  ArrowLeft, ThumbsUp, ThumbsDown, ShieldBan, ShieldCheck, FileText,
} from "lucide-react";
import { formatDate, formatId } from "@/lib/utils";
import { ReportStatusBadge } from "@/components/ReportStatusBadge";
import { MarkdownRenderer } from "@/components/MarkdownRenderer";
import { useAutoScopeProject } from "@/hooks/useAutoScopeProject";

/**
 * Unscoped, id-keyed query roots on this page. Their data is identical
 * regardless of the selected project, so we preserve them when auto-scoping to
 * the insight's project (see {@link useAutoScopeProject}) to avoid a flash.
 */
const INSIGHT_DETAIL_UNSCOPED_QUERY_ROOTS = ["insight", "insight-reports"] as const;

export function InsightDetail() {
  const { id } = useParams<{ id: string }>();
  const queryClient = useQueryClient();

  const { data: insight, isLoading, error } = useQuery({
    queryKey: ["insight", id],
    queryFn: () => api.getInsight(id!),
    enabled: !!id,
  });

  // Scope the app to this insight's project when the URL is opened directly.
  // Route is ungated; preserve this page's own unscoped queries to avoid a flash.
  useAutoScopeProject(id, insight?.projectId, INSIGHT_DETAIL_UNSCOPED_QUERY_ROOTS);

  const { data: reports = [] } = useQuery({
    queryKey: ["insight-reports", id],
    queryFn: () => api.getInsightReports(id!),
    enabled: !!id,
  });

  const upvoteMutation = useMutation({
    mutationFn: () => api.upvoteInsight(id!),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["insight", id] }),
  });

  const downvoteMutation = useMutation({
    mutationFn: () => api.downvoteInsight(id!),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["insight", id] }),
  });

  const blockMutation = useMutation({
    mutationFn: (blocked: boolean) =>
      blocked ? api.blockInsight(id!) : api.unblockInsight(id!),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["insight", id] }),
  });

  if (isLoading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-8 w-48" />
        <Skeleton className="h-6 w-96" />
        <Skeleton className="h-64 w-full" />
      </div>
    );
  }

  if (error || !insight) {
    return (
      <div className="text-center py-12 text-destructive">
        {error instanceof Error ? error.message : "Insight not found"}
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div className="space-y-1">
          <Link to="/insights" className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground mb-2">
            <ArrowLeft className="h-3.5 w-3.5" /> Back to insights
          </Link>
          <h1 className="text-2xl font-bold tracking-tight">{insight.title}</h1>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <span>Created {formatDate(insight.createdAt)}</span>
            <span>·</span>
            <span>{insight.createdBy === "agent" ? "Generated by agent" : "Created by user"}</span>
            {insight.sourceReportId && (
              <>
                <span>·</span>
                <Link to={`/reports/${insight.sourceReportId}`} className="text-primary hover:underline">
                  Source report
                </Link>
              </>
            )}
          </div>
        </div>
      </div>

      {/* Metadata cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="pt-4 pb-4">
            <div className="text-sm text-muted-foreground">Category</div>
            <div className="mt-1">
              {insight.category ? (
                <Badge variant="secondary">{insight.category}</Badge>
              ) : (
                <span className="text-muted-foreground">–</span>
              )}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-4 pb-4">
            <div className="text-sm text-muted-foreground">References</div>
            <div className="text-2xl font-bold mt-1">{insight.referenceCount}</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-4 pb-4">
            <div className="text-sm text-muted-foreground">Votes</div>
            <div className="flex items-center gap-2 mt-1">
              <Button
                variant="outline"
                size="sm"
                className="h-8 gap-1"
                onClick={() => upvoteMutation.mutate()}
                disabled={upvoteMutation.isPending}
              >
                <ThumbsUp className="h-3.5 w-3.5" /> {insight.upvotes}
              </Button>
              <Button
                variant="outline"
                size="sm"
                className="h-8 gap-1"
                onClick={() => downvoteMutation.mutate()}
                disabled={downvoteMutation.isPending}
              >
                <ThumbsDown className="h-3.5 w-3.5" /> {insight.downvotes}
              </Button>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-4 pb-4">
            <div className="text-sm text-muted-foreground">Status</div>
            <div className="mt-1">
              <Button
                variant={insight.blocked ? "destructive" : "outline"}
                size="sm"
                className="h-8 gap-1"
                onClick={() => blockMutation.mutate(!insight.blocked)}
                disabled={blockMutation.isPending}
              >
                {insight.blocked ? (
                  <><ShieldBan className="h-3.5 w-3.5" /> Blocked</>
                ) : (
                  <><ShieldCheck className="h-3.5 w-3.5" /> Active</>
                )}
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Tags */}
      {insight.tags && insight.tags.length > 0 && (
        <div className="flex flex-wrap gap-1.5">
          {insight.tags.map((tag) => (
            <Badge key={tag} variant="outline">{tag}</Badge>
          ))}
        </div>
      )}

      {/* Description (Markdown) */}
      <Card>
        <CardHeader>
          <CardTitle>Description</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="prose prose-sm dark:prose-invert max-w-none">
            <MarkdownRenderer githubAlerts>
              {insight.description}
            </MarkdownRenderer>
          </div>
        </CardContent>
      </Card>

      {/* Referenced by reports */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-4 w-4" />
            Referenced by Reports ({reports.length})
          </CardTitle>
        </CardHeader>
        <CardContent>
          {reports.length > 0 ? (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[120px]">Report ID</TableHead>
                  <TableHead>Run ID</TableHead>
                  <TableHead className="w-[100px]">Status</TableHead>
                  <TableHead className="w-[100px]">Model</TableHead>
                  <TableHead className="w-[160px]">Created</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {reports.map((report) => (
                  <TableRow key={report._id}>
                    <TableCell>
                      <Link
                        to={`/reports/${report._id}`}
                        className="font-mono text-xs text-primary hover:underline"
                      >
                        {formatId(report._id)}
                      </Link>
                    </TableCell>
                    <TableCell>
                      <Link
                        to={`/runs/${report.requestId}`}
                        className="font-mono text-xs text-muted-foreground hover:text-foreground hover:underline"
                      >
                        {formatId(report.requestId)}
                      </Link>
                    </TableCell>
                    <TableCell>
                      <ReportStatusBadge status={report.status} />
                    </TableCell>
                    <TableCell className="text-sm text-muted-foreground">
                      {report.reporter?.model ?? "–"}
                    </TableCell>
                    <TableCell className="text-sm text-muted-foreground">
                      {formatDate(report.createdAt)}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          ) : (
            <p className="text-sm text-muted-foreground">
              No reports reference this insight yet.
            </p>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
